name: second workflow
on: push

jobs:
  job1:
    name: first
    runs-on: ubuntu-latest
    steps:
      - name: running fisrt command
        run: |
          ls -la
          sleep 5
        
  job2:
    name: sencond
    needs: job1
    runs-on: windows-2022
    steps:
      - name: checking windows version
        run: |
          winver
          ipconfig
  job3:
    name: third
    runs-on: ubuntu-latest
    steps:
    - name: testing
      run: |
         pwd
         cat /etc/os-release
  job4:
    name: fourth
    needs: [job1, job3]
    runs-on: macos-latest
    steps:
    - name: mac os cmds
      run: |
        ifconfig
        date
        ls -la
        whoami
        date
         
         
    
